# keymap.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
[[manager.prepend_keymap]]
run = """shell 'zip -r "$0".zip $(basename "$0")' --interactive"""
on = ["u", "z"]
desc = "Zip hovered file/directory"

[[manager.prepend_keymap]]
on = "<Space>"
run = "toggle"
desc = "Toggle selection"
