# yazi.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode = "size"
show_hidden = true
show_symlink = false

[preview]
max_width = 1920
max_height = 1080

[open]
prepend_rules = [
    { name = "*.rnote", use = "open" },
    { name = "*/", use = [
        "open",
        "edit",
    ] },
]
