"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
\\[$directory\
( on( $git_branch))\
( via( $rust)( $python))\\]\
$character """

[character]
format = "$symbol"
success_symbol = "[%](fg:bright-cyan)"
error_symbol = "[%](fg:bright-red)"

[directory]
format = "[$path]($style)( [\\($read_only\\)]($read_only_style))"
read_only = "ro"
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 1
style = "fg:bright-green"
read_only_style = "fg:bright-red"

[git_branch]
format = "[$symbol $branch]($style)"
symbol = "\\(git\\)"
style = "fg:bright-purple"

[python]
format = "[$symbol ($virtualenv )($version)]($style)"
symbol = "\\(py\\)"
style = "fg:bright-yellow"

[rust]
format = "[$symbol ($version)]($style)"
symbol = "\\(rs\\)"
style = "fg:bright-red"
