################################################################################
# Common
################################################################################

color_theme = "jungle"
vim_keys = true
theme_background = false
rounded_corners = false
save_config_on_exit = false
