"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "gruvbox"

format = """
$directory\
(on $hostname$git_branch$container)\
(via $rust$python)
$character """

[palettes.gruvbox]
orange = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
aqua = "#8ec07c"
purple = "#d3869b"
red = "#fb4934"

[character]
format = "$symbol"
success_symbol = '[\$](fg:green)'
error_symbol = "[#](fg:red)"

[directory]
format = "[$path ]($style)([$read_only ]($read_only_style))"
read_only = "󰌾"
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 2
style = "fg:yellow"
read_only_style = "fg:orange"

[git_branch]
format = "[$symbol$branch ]($style)"
style = "fg:purple"

[python]
format = "[$symbol($virtualenv )($version )]($style)"
symbol = " "
style = "fg:orange"

[rust]
format = "[$symbol($version )]($style)"
symbol = " "
style = "fg:red"

[hostname]
format = "[$ssh_symbol$hostname ]($style)"
ssh_only = true
ssh_symbol = "󰣀 "
style = "fg:orange"

[container]
format = "[$symbol$name ]($style)"
symbol = " "
style = "fg:aqua"
