# starship.toml

# config schema
"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "gruvbox"
format = """
[$directory](fg:bg bg:yellow)\
[](fg:yellow bg:orange)\
[$container$rust$python$git_branch$hostname](fg:bg bg:orange)\
[](fg:orange bg:red)\
[$character](fg:bg bg:red)\
[](fg:red)\
[ ](none)"""

[palettes.gruvbox]
bg = "#1d2021"
red = "#fb4934"
orange = "#fe8019"
yellow = "#fabd2f"

[character]
format = "$symbol"
success_symbol = ' \$ '
error_symbol = " # "
vimcmd_symbol = " N "
vimcmd_replace_one_symbol = " R "
vimcmd_replace_symbol = " R "
vimcmd_visual_symbol = " V "

[directory]
format = " $path ($read_only)"
read_only = "󰌾 "
truncation_symbol = ""
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = " $symbol$branch "

[python]
format = " $symbol($virtualenv )($version )"
symbol = " "

[rust]
format = " $symbol($version )"
symbol = " "

[hostname]
format = " $ssh_symbol$hostname "
ssh_only = true
ssh_symbol = "󰣀 "

[container]
format = " $symbol$name "
symbol = " "
