set -g @base00 "#$base00"
set -g @base01 "#$base01"
set -g @base02 "#$base02"
set -g @base03 "#$base03"
set -g @base04 "#$base04"
set -g @base05 "#$base05"
set -g @base06 "#$base06"
set -g @base07 "#$base07"
set -g @base08 "#$base08"
set -g @base09 "#$base09"
set -g @base0A "#$base0A"
set -g @base0B "#$base0B"
set -g @base0C "#$base0C"
set -g @base0D "#$base0D"
set -g @base0E "#$base0E"
set -g @base0F "#$base0F"
