[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "fish"
indent = { tab-width = 4, unit = "    "}
auto-format = false

[[language]]
name = "zig"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
language-servers = [ "pylsp" ]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
# flake8 setup
flake8 = { enabled = true }
pycodestyle = { enabled = false }
mccabe = { enabled = false }
pyflakes = { enabled = false }

# yapf as formatter
yapf = { enabled = true }

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "yaml"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "latex"
indent = { tab-width = 4, unit = "    " }
