# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

disableStartupPopups: true
promptToReturnFromSubprocess: false
notARepository: skip

gui:
  theme:
    activeBorderColor:
      - "#97BACC"
      - bold

    inactiveBorderColor:
      - "#556753"

    searchingActiveBorderColor:
      - "#DF867A"
      - bold

    optionsTextColor:
      - "#63AFA0"

    selectedLineBgColor:
      - "#2D382E"

    inactiveViewSelectedLineBgColor:
      - "#1D261F"
      - bold

    cherryPickedCommitFgColor:
      - "#131914"

    cherryPickedCommitBgColor:
      - "#DF867A"

    markedBaseCommitFgColor:
      - "#63AFA0"

    markedBaseCommitBgColor:
      - "#DAC05B"

    unstagedChangesColor:
      - "#DF867A"

    defaultFgColor:
      - "#D4DCC2"

  authorColors:
    "*": "#63AFA0"

  border: single
