################################################################################
# Options 
################################################################################
set -g default-terminal 'tmux-256color'
set -as terminal-features ',xterm-256color:RGB'
set -as terminal-features ',*:usstyle'

set -ga update-environment SSH_AUTH_SOCK
set -ga update-environment SSH_CONNECTION

set -g mouse on
set -g set-titles on
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
set -g extended-keys on
set -g extended-keys-format csi-u

set -g mode-keys vi
set -g status-keys emacs
set -g set-titles-string "#T"
set -g base-index 1
set -g status-interval 100
set -g repeat-time 1000
set -s escape-time 50
setw -g renumber-windows on
setw -g pane-base-index 1

################################################################################
# Theme
################################################################################
set -g @base00 "#131914"
set -g @base01 "#1D261F"
set -g @base02 "#2D382E"
set -g @base03 "#556753"
set -g @base04 "#87967F"
set -g @base05 "#D4DCC2"
set -g @base06 "#E7EED3"
set -g @base07 "#F5F9EA"
set -g @base08 "#DF867A"
set -g @base09 "#EDA665"
set -g @base0A "#DAC05B"
set -g @base0B "#84B87E"
set -g @base0C "#63AFA0"
set -g @base0D "#97BACC"
set -g @base0E "#B89CC1"
set -g @base0F "#AA7466"

set -g status-position top
set -g status-justify centre
set -g status-style "bg=#{@base02},fg=#{@base04}"
set -g message-style "bg=#{@base02},fg=#{@base04}"

set -g status-right " #{p-28:#{=|27|>:#{user}@#{host}}} "
set -g status-left " #{?client_prefix,#[fg=#{@base08}],}#{p28:#{=|27|>:#{session_name}}}#[default] "
set -g status-right-length 30
set -g status-left-length 30

setw -g window-status-current-style "fg=#{@base0B}"
setw -g window-status-current-format "#I #W"
setw -g window-status-style "fg=#{@base03}"
setw -g window-status-format "#I #W"
setw -g window-status-bell-style "bg=#{@base02},fg=#{@base04}"
set -g window-status-separator "  "

set -g pane-border-style "fg=#{@base03}"
set -g pane-active-border-style "fg=#{@base0B}"
setw -g pane-border-format ""

set -g copy-mode-match-style "bg=#{@base0A},fg=#{@base00}"
set -g copy-mode-current-match-style "bg=#{@base08},fg=#{@base00}"
set -g mode-style "bg=#{@base02}"

################################################################################
# Keybinds
################################################################################
unbind C-b
unbind %
unbind '"'

set -g prefix C-a
bind C-a send-prefix
bind Enter copy-mode
bind x kill-pane
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind r source-file ~/.config/tmux/tmux.conf

bind _ split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}" "$SHELL"

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down
